# ______________________________________________________________________________________#
# _________________________________ CONSTANTS __________________________________________#
# ______________________________________________________________________________________#

SIMILARITY_THRESHOLD = 0.8  # Cosine similarity threshold for embeddings
WHITESPACE_THRESHOLD = 0.8  # Threshold for whitespace node detection